---
title: "BMI_final_project"
author: "Junting Ren Uni:jr3755"
date: "December 9, 2017"
output: html_document
---

```{r setup, include=FALSE}
knitr::opts_chunk$set(echo = TRUE)
library(leaps)
library(readxl)
library(janitor)
library(psych)
library(HH)
library(purrr)
library(tidyr)
library(ggplot2)
library(boot) 
library(tidyverse)
```

##reading and cleaning the data
```{r reading and cleaning the data}
gh_project_raw <- read_excel("GHProject_Dataset.xlsx", sheet = 1) %>% 
  clean_names() %>% 
  mutate(mews = as.factor(mews), cindex = as.factor(cindex), 
         icu_flag = as.factor(icu_flag), gender = as.factor(gender), race =
           as.factor(race), religion = as.factor(religion), maritalstatus =
           as.factor(maritalstatus), insurancetype = as.factor(insurancetype)) 

gh_duplicate <- gh_project_raw[gh_project_raw$patientid %in% gh_project_raw$patientid[duplicated(gh_project_raw$patientid)],] %>% 
  group_by(patientid) %>% 
  count() 

##We got 69 patients with more than 1 visit, 68 had 2 visits, 1 had 3 visits.
dim(gh_duplicate)

gh_project <- gh_project_raw %>% 
  arrange(patientid, visitid) %>% 
  filter(!duplicated(patientid))

```

```{r descriptive statistics}
des_stat = gh_project %>%
  select(-gender, -race, -maritalstatus, -facilityname, -insurancetype, -facilityzip, -admitdtm, -religion, -postalcode, -is30dayreadmit, -patientid, -visitid -mews, -cindex, -icu_flag) %>%
  describe(na.rm = TRUE)

#there is a BMI of 3.1 (min) and 122.7.  Both of these are impossible
#there is a min temp of 11.85 52.275.  Again, both of these are incorrect.
# funny bp values as well??

gender = table(gh_project$gender) %>% prop.table()
race = table(gh_project$race) %>% prop.table()
marital_status = table(gh_project$maritalstatus)  %>% prop.table()
insurance = table(gh_project$insurancetype) %>% prop.table()
religion = table(gh_project$religion) %>% prop.table()
readmit = table(gh_project$is30dayreadmit) %>% prop.table()
mews = table(gh_project$mews) %>% prop.table()
cindex = table(gh_project$cindex) %>% prop.table()
icu_flag = table(gh_project$icu_flag) %>% prop.table()



gh_project = gh_project %>%
  filter(bmi < 100 | is.na(bmi)) %>%
  filter(temperature < 45 | is.na(temperature)) %>%
  filter(temperature > 15 | is.na(temperature))
  
```

```{r recoding categorical var}
library(forcats)
gh_project$race = fct_collapse(gh_project$race, White = "White", Non_White = c("African Amer/Black","Asian","Native Amer/Alaskan","Natv Hawaii/Pacf Isl", "Other/Multiracial"))

gh_project$maritalstatus = fct_collapse(gh_project$maritalstatus, Married = "Married", Not_Married = c("Civil Union","Divorced","Separated","Single", "Widowed"))

gh_project$insurancetype = fct_collapse(gh_project$insurancetype, Private = "Private", Not_Private = c("Medicaid","Medicare"))

gh_project$religion = fct_collapse(gh_project$religion, Catholic = "Catholic", Christian = "Christian", Other = c("Angelican","Hebrew","Hindu","Islam", "Jewish", "Mormon", "No Affiliation", "Non Denominational", "Other"))

gh_project$insurancetype = fct_collapse(gh_project$insurancetype, Private = "Private", Not_Private = c("Medicaid","Medicare"))

gh_project$mews = fct_collapse(gh_project$mews, Normal = c("0", "1"), Increase_caution = c("2", "3"), Further_deterioration = c("4", "5"), Immediate_action_required = c("6", "7", "8", "9", "10", "11", "12", "14"))

gh_project$cindex = fct_collapse(gh_project$cindex, normal = "0", mild = c("1", "2"), moderate = "3", severe = "5")

gh_project = gh_project %>%
  filter(icu_flag == "0")
# model only applies to patients who did not go to ICU
```


```{r plots}

gh_project %>%
  keep(is.numeric) %>% 
  gather() %>% 
  ggplot(aes(value)) +
    facet_wrap(~ key, scales = "free") +
    geom_histogram()

attach(gh_project)

hist(losdays2)
hist(log(losdays2))
```

```{r transformations}
gh_project = 
  gh_project %>%
  mutate(log_losdays2 = log(losdays2))

#write dataset as csv
#write_csv(sas_train_data, path = "C:/Users/mphad/Documents/1st semester/Intro to Biostats/sas_train_data.csv")
```

```{r model selection}
set.seed(1)
train <- sample(3543,1772)

sas_train_data <- gh_project[train,]

best <- function(model, ...) 
{
  subsets <- regsubsets(formula(model), model.frame(model), ...)
  subsets <- with(summary(subsets),
                  cbind(p = as.numeric(rownames(which)), which, rss, rsq, adjr2, cp, bic))
  
  return(subsets)
}  

##Final datset for model
gh_project <- gh_project %>% 
  select(-patientid, -visitid, -admitdtm, -icu_flag, -postalcode, 
         -facilityname, -facilityzip, -loshours, -losdays2)

multi_fit <- lm(log_losdays2 ~ ., data = gh_project, subset = train)


View(best(multi_fit, nvmax = 30, method = "exhaustive"))



final_model <- lm(log_losdays2 ~ is30dayreadmit + cindex + 
                    evisit + ageyear + heartrate +
                    insurancetype + bpsystolic + temperature +
                    respirationrate, data = gh_project[train,])

vif(final_model)
gh_project %>% 
  dplyr::select(bpdiastolic, bpsystolic) %>% 
  na.omit() %>% 
  cor(x = .)
```


```{r final model}
plot_crit <-regsubsets(log_losdays2 ~ ., data = gh_project[train,], nvmax = 30) 
rs<-summary(plot_crit)
par(mfrow=c(2,2))
plot(2:23, rs$cp, xlab="No of parameters", ylab="Cp Statistic") 
abline(0,1)
plot(2:23, rs$adjr2, xlab="No of parameters", ylab="Adj R2")



```



```{r check model assumption}
par(mfrow = c(2,2))
plot(final_model)
# normality assumption - skewed to the left

# obs 1112, 1581, 1669


gh_project_raw %>%
  arrange(losdays2)
# all 3 subjects lowest losdays2
# lets see after deleting

#outliers in y  (29)
stu_res<-rstandard(final_model)
outliers_y = as.data.frame(stu_res)
n = c(1:1753)
outliers_y = cbind(n,outliers_y)

outliers_y = outliers_y %>%
  filter(abs(stu_res)>2.5) %>%
  mutate(stu = stu_res[abs(stu_res)])
  
#outliers in x, hat value >0.5 very high, >2p/n = 0.0087 high, 0.2~0.5 moderate (1) 
#15 parameters
hat =  hatvalues(final_model)
hat = round(hat,4)
n = c(1:1753)
hat = cbind(n,hat)
hat_inf = as.data.frame(hat)%>% 
  clean_names()%>%
  filter(hat > 0.2)

#influential observation (parameters = 16)
#cook's distance >0.5, >0.2
cook = cooks.distance(final_model)
cook = as.data.frame(cook) 
cook%>%
filter(cook>0.2)
#no cook's distance > 0.2


#dffits>2sqrt(p/n) = 0.1323 or 1
#influence = influence.measures(final_model)
#summary(influence)
#plot(rstudent(final_model) ~ hatvalues(final_model))
dffit = dffits(final_model)
dffit = cbind(n,dffit)
dffit = as.data.frame(dffit) 
inf_dffit = dffit %>%
  filter(abs(dffit)>0.1323)
num_dffit = inf_dffit$n#148

#influential x outliers 
x_inf = left_join(hat_inf,dffit,by = "n")%>%
  filter(abs(dffit)>0.137)
num_inf = x_inf$n #1

#influential y outliers 
y_inf = left_join(outliers_y,dffit,by = "n")%>%
  filter(abs(dffit)>0.137)
num_inf = c(num_inf,y_inf$n)%>%
  unique() #30

#omit NAs in the dataset 
gh_project_remove = sas_train_data %>%
  dplyr::select(is30dayreadmit, cindex, evisit, ageyear, insurancetype, heartrate, respirationrate, log_losdays2, temperature,bpsystolic) %>%
  na.omit()

#remove influential points
gh_project_remove1 = gh_project_remove
for(i in 1:131){
gh_project_remove1 = gh_project_remove1[-num_dffit[i],]}

final_model_remove1 <- lm(log_losdays2 ~ is30dayreadmit + cindex + 
                    evisit + ageyear + heartrate +
                    insurancetype + bpsystolic + temperature +
                    respirationrate, data = gh_project_remove1)

summary(final_model_remove1)

#remove influential x,y outliers 
gh_project_remove2 = gh_project_remove
for(i in 1:length(num_inf)){
gh_project_remove2 = gh_project_remove2[-num_inf[i],]}

final_model_remove2 <- lm(log_losdays2 ~ is30dayreadmit + cindex + 
                    evisit + ageyear + heartrate +
                    insurancetype + bpsystolic + temperature +
                    respirationrate,, data = gh_project_remove2)

summary(final_model_remove2)

summary(final_model)

par(mfrow=c(2,2))
plot(final_model_remove1)

par(mfrow=c(2,2))
plot(final_model_remove2)

#remove 3 observations based on residuals
gh_project_remove3 = gh_project_remove
x = c(1112, 1581, 1669)
gh_project_remove3 = gh_project_remove3[-x,]
final_model_remove3 <- lm(log_losdays2 ~ is30dayreadmit + cindex + 
                    evisit + ageyear + heartrate +
                    insurancetype + bpsystolic + temperature +
                    respirationrate, data = gh_project_remove3)

summary(final_model_remove3)

par(mfrow=c(2,2))
plot(final_model_remove3)
```



```{r model validation}

#bootstrap to access the model coefficient varibility

boot.fn <- function(data, index){
	return(coef(lm(log_losdays2 ~ is30dayreadmit + cindex + 
                    evisit + ageyear + temperature +
                    insurancetype + bpsystolic + heartrate +
                    respirationrate, subset = index, 
	               data = gh_project[train, ])))
}

boot.adj.r <- function(data, index){
	return(summary(lm(log_losdays2 ~ is30dayreadmit + cindex + 
                    evisit + ageyear + temperature +
                    insurancetype + bpsystolic + heartrate +
                    respirationrate, subset = index, 
	               data = gh_project[train, ]))$adj.r.squared)
}





boot_coef <- boot(gh_project[train,], boot.fn, 100)
boot_adj_r <- boot(gh_project[train,], boot.adj.r, 100)

# How does it compare to the original (non-bootstrap) estimates?
summary(final_model)

##Assessing the prediction
mean((mpg-predict(lm.fit, Auto))[-train]^2)

```


###Conclusion